<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="xs oape" version="3.0"
    xmlns:oape="https://openarabicpe.github.io/ns" xmlns:tei="http://www.tei-c.org/ns/1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output encoding="UTF-8" indent="yes" method="xml"/>
    <xsl:include href="../../oxygen-project/OpenArabicPE_parameters.xsl"/>
    <xsl:template match="/">
        <tei:TEI>
            <tei:teiHeader>
                <tei:fileDesc>
                    <tei:titleStmt>
                        <tei:title>Bibliographic metadata from Sakhrit: </tei:title>
                        <xsl:copy-of select="$p_editor"/>
                    </tei:titleStmt>
                    <tei:publicationStmt>
                        <p>Publication Information</p>
                    </tei:publicationStmt>
                    <tei:sourceDesc>
                        <p>This file was generated by automatic conversion of bibliographic output from R.</p>
                    </tei:sourceDesc>
                </tei:fileDesc>
                <tei:revisionDesc>
                    <tei:change>
                        <xsl:attribute name="when"
                            select="format-date(current-date(), '[Y0001]-[M01]-[D01]')"/>
                        <xsl:attribute name="who" select="concat('#', $p_id-editor)"/>
                        <xsl:attribute name="xml:id" select="$p_id-change"/>
                        <xsl:attribute name="xml:lang" select="'en'"/>
                        <xsl:text>Generated this file by automatic conversion of </xsl:text>
                        <xsl:value-of select="base-uri()"/>
                        <xsl:text>.</xsl:text>
                    </tei:change>
                </tei:revisionDesc>
            </tei:teiHeader>
            <tei:text>
                <tei:body>
                    <tei:div>
                        <xsl:apply-templates/>
                    </tei:div>
                </tei:body>
            </tei:text>
        </tei:TEI>
    </xsl:template>
    <xsl:template match="oape:tibble">
        <tei:listBibl>
            <xsl:apply-templates/>
        </tei:listBibl>
    </xsl:template>
    <xsl:template match="oape:row">
        <tei:biblStruct corresp="sakhrit:aid:{oape:article.id}" xml:lang="ar">
            <tei:analytic corresp="sakhrit:aid:{oape:article.id}">
                <xsl:apply-templates select="oape:author.name"/>
                <xsl:apply-templates select="oape:article.title"/>
                <xsl:apply-templates select="oape:article.url"/>
                <xsl:apply-templates select="oape:article.id"/>
            </tei:analytic>
            <tei:monogr corresp="sakhrit:iid:{oape:issue.id}">
                <xsl:apply-templates select="oape:journal.title"/>
                <xsl:apply-templates select="oape:journal.id"/>
                <xsl:apply-templates select="oape:issue.id"/>
                <tei:textLang mainLang="ar"/>
                <tei:imprint>
                    <!-- no information on editors etc. available -->
                    <xsl:apply-templates select="oape:date.publication"/>
                </tei:imprint>
                <xsl:apply-templates select="oape:issue"/>
                <xsl:apply-templates select="oape:page.from"/>
            </tei:monogr>
        </tei:biblStruct>
    </xsl:template>
    <xsl:template match="oape:date.publication">
        <tei:date when="{parent::oape:row/oape:date.publication.iso}">
            <xsl:apply-templates/>
        </tei:date>
    </xsl:template>
    <xsl:template match="oape:page.from">
        <tei:biblScope from="{.}" unit="page">
            <xsl:apply-templates/>
        </tei:biblScope>
    </xsl:template>
    <xsl:template match="oape:issue">
        <tei:biblScope unit="issue">
            <!-- one could do some regex here -->
            <xsl:apply-templates/>
        </tei:biblScope>
    </xsl:template>
    <xsl:template match="oape:journal.title">
        <tei:title corresp="sakhrit:jid:{parent::oape:row/oape:journal.id}" level="j">
            <xsl:apply-templates/>
        </tei:title>
    </xsl:template>
    <xsl:template match="oape:article.title">
        <tei:title level="a">
            <xsl:apply-templates/>
        </tei:title>
    </xsl:template>
    <xsl:template match="oape:article.url">
        <tei:idno type="url" xml:lang="en">
            <xsl:apply-templates/>
        </tei:idno>
    </xsl:template>
    <xsl:template match="oape:article.id">
        <tei:idno type="aid">
            <xsl:apply-templates/>
        </tei:idno>
    </xsl:template>
    <xsl:template match="oape:journal.id">
        <tei:idno type="jid">
            <xsl:apply-templates/>
        </tei:idno>
    </xsl:template>
    <xsl:template match="oape:issue.id">
        <tei:idno type="iid">
            <xsl:apply-templates/>
        </tei:idno>
    </xsl:template>
    <xsl:template match="oape:author.name">
        <xsl:choose>
            <xsl:when test=". = 'NA'"/>
            <xsl:when test=". = ''"/>
            <xsl:otherwise>
                <tei:author>
                    <tei:persName>
                        <xsl:apply-templates/>
                    </tei:persName>
                </tei:author>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
</xsl:stylesheet>
